#!/bin/bash

SERVER="/boot/server.txt"
if[ ! -f $SERVER]; then
    rm /etc/nomad.d/server.hcl
    rm /etc/consul.d/server.hcl
    rm /etc/avahi/services/picluster.service
    touch "/boot/client.txt"
fi

rm $0